config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :users
  resources :views
  resources :users
  resources :movies

  root to: 'home#welcome'
    get '/welcome', to: 'home#welcome'
    get '/movies', to: 'home#movies'
    get '/users', to: 'home#users'
    get '/views', to: 'home#views'
    get '/search', to: 'home#search'

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :users
  has_many :views, through: :users

  



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :views
  has_many :movies, through: :viewings
end

app/models/view.rb
class View < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def after_sign_in_path_for(resource)
    secret_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    
  end

  def movies
    
  end

  def users
    
  end

  def views
    
  end

  def welcome
    
  end
 
 def search
   case params[:options]

   when 'categories' then redirect_to(categories_path)
   when 'recipes' then redirect_to('http://bbcgoodfood.com')
   # when 'google' then redirect_to('http://www.google.co.uk')

   else render :welcome
       
   end
 end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  
  def params
    get'/' do
      @title = params[:title]

      if @title && @title > ''
        @title = @title.gsub(' ','+')
        url = "http://www.omdbapi.com/?t=#{@title}"
        @search_results = HTTParty.get(url)

        sql = "INSERT INTO movies (
          title,
          year,
          rated,
          runtime,
          genre,
          director,
          writers,
          actors,
          poster,
          plot)
VALUES (
  '#{@search_results['Title'].gsub("'","''")}',
  #{@search_results['Year'].to_i},
  '#{@search_results['Rated'].gsub("'","''")}',
  '#{@search_results['Runtime'].gsub("'","''")}',
  '#{@search_results['Genre'].gsub("'","''")}',
  '#{@search_results['Director'].gsub("'","''")}',
  '#{@search_results['Writer'].gsub("'","''")}',
  '#{@search_results['Actors'].gsub("'","''")}',
  '#{@search_results['Poster'].gsub("'","''")}',
  '#{@search_results['Plot'].gsub("'","''")}'
  )"
@db.exec(sql)
      #save in my DB
    end
    
  end
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :year, :rate, :genre, :director, :writer, :actors)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_view, only: [:show, :edit, :update, :destroy]

  # GET /views
  # GET /views.json
  def index
    @views = View.all
  end

  # GET /views/1
  # GET /views/1.json
  def show
  end

  # GET /views/new
  def new
    @view = View.new
  end

  # GET /views/1/edit
  def edit
  end

  # POST /views
  # POST /views.json
  def create
    @view = View.new(view_params)

    respond_to do |format|
      if @view.save
        format.html { redirect_to @view, notice: 'View was successfully created.' }
        format.json { render :show, status: :created, location: @view }
      else
        format.html { render :new }
        format.json { render json: @view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /views/1
  # PATCH/PUT /views/1.json
  def update
    respond_to do |format|
      if @view.update(view_params)
        format.html { redirect_to @view, notice: 'View was successfully updated.' }
        format.json { render :show, status: :ok, location: @view }
      else
        format.html { render :edit }
        format.json { render json: @view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /views/1
  # DELETE /views/1.json
  def destroy
    @view.destroy
    respond_to do |format|
      format.html { redirect_to views_url, notice: 'View was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_view
      @view = View.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def view_params
      params.require(:view).permit(:user_id, :movie_id, :place_of_viewing, :review)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/home/welcome.html.erb
<h1>Welcome to world movie resource </h1>


<%= form_tag(search_path, method: :get) do %>
  <p> Search For movies</p>
  <%= text_field_tag :options %>
  <%=submit_tag "Search!" %>

  

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyMovie</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class='login'>
    <% if current_user %>
      <%= current_user.email %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Register", new_user_registration_path %>
    <% end %>
  </div>

  <li><%= link_to "home", root_path %></li>
 <li><%= link_to "users", users_path %></li>
 <li><%= link_to "views", views_path %></li>
 <li><%=link_to 'movies', movies_path %></li>
 </ul>
 </nav>
<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.number_field :rate %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :writer %><br>
    <%= f.text_field :writer %>
  </div>
  <div class="field">
    <%= f.label :actors %><br>
    <%= f.text_field :actors %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Rate</th>
      <th>Genre</th>
      <th>Director</th>
      <th>Writer</th>
      <th>Actors</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.year %></td>
        <td><%= movie.rate %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.director %></td>
        <td><%= movie.writer %></td>
        <td><%= movie.actors %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @movie.rate %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Writer:</strong>
  <%= @movie.writer %>
</p>

<p>
  <strong>Actors:</strong>
  <%= @movie.actors %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/views/_form.html.erb
<%= form_for(@view) do |f| %>
  <% if @view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@view.errors.count, "error") %> prohibited this view from being saved:</h2>

      <ul>
      <% @view.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.number_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :place_of_viewing %><br>
    <%= f.text_field :place_of_viewing %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_field :review %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/views/edit.html.erb
<h1>Editing View</h1>

<%= render 'form' %>

<%= link_to 'Show', @view %> |
<%= link_to 'Back', views_path %>

app/views/views/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Views</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Movie</th>
      <th>Place of viewing</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @views.each do |view| %>
      <tr>
        <td><%= view.user_id %></td>
        <td><%= view.movie_id %></td>
        <td><%= view.place_of_viewing %></td>
        <td><%= view.review %></td>
        <td><%= link_to 'Show', view %></td>
        <td><%= link_to 'Edit', edit_view_path(view) %></td>
        <td><%= link_to 'Destroy', view, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New View', new_view_path %>

app/views/views/new.html.erb
<h1>New View</h1>

<%= render 'form' %>

<%= link_to 'Back', views_path %>

app/views/views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @view.user_id %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @view.movie_id %>
</p>

<p>
  <strong>Place of viewing:</strong>
  <%= @view.place_of_viewing %>
</p>

<p>
  <strong>Review:</strong>
  <%= @view.review %>
</p>

<%= link_to 'Edit', edit_view_path(@view) %> |
<%= link_to 'Back', views_path %>